name: medica2
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & icons
  cupertino_icons: ^1.0.8

  # Firebase packages
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.1

  # Utilities
  fluttertoast: ^9.0.0
  image_picker: ^1.2.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.10.1
  path: ^1.9.0
  uuid: ^4.2.1
  http: ^1.5.0
  dio: ^5.4.0
  http_parser: ^4.0.2

  # ✅ REQUIRED FOR IMAGE FIX (MODEL ACCURACY)
  image: ^4.1.3
  path_provider: ^2.1.2

  # ✅ FIXED VERSION
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
